name: NoMoreDroppedItems
version: '${version}'
main: club.aurorapvp.nomoredroppeditems.NoMoreDroppedItems
api-version: '1.20'
authors: [ Villagers654 ]
description: Gets rid of dropped items without disabling dropping items
website: aurorapvp.club

dependencies:
  server:
    WorldGuard:
      required: true